# Generated by Django 4.2.4 on 2023-08-10 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_title', models.CharField(max_length=200)),
                ('sku_title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_title', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_title', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sales_date', models.DateField()),
                ('total_amount', models.IntegerField()),
                ('beer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.beer')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_title', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_title', models.CharField(max_length=200)),
                ('location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.location')),
            ],
        ),
        migrations.CreateModel(
            name='SalesBeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.beer')),
                ('sales_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.sales')),
            ],
        ),
        migrations.AddField(
            model_name='sales',
            name='store_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.store'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('beer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.beer')),
                ('storage_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.storage')),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='Packaging_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.packaging'),
        ),
        migrations.AddField(
            model_name='beer',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.company'),
        ),
        migrations.AddField(
            model_name='beer',
            name='storage_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.storage'),
        ),
    ]
